# Generated by Django 3.2.8 on 2023-04-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=40)),
                ('product_category', models.CharField(choices=[('bakery', 'Bakery'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('beverages', 'Beverages'), ('dairy', 'Dairy'), (
                    'meats', 'Meats'), ('coffe & tea', 'Coffe & Tea'), ('cans & jars', 'Cans & Jars'), ('herbs & spices', 'Herbs & Spices'), ('frozen', 'Frozen'), ('hygiene', 'Hygiene')], max_length=20)),
                ('producer', models.CharField(default='', max_length=40)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True,
                 upload_to='product_images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[
                 (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='supermarket_app.product')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='supermarket_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='supermarket_app.Product')),
                ('user', models.ManyToManyField(to='supermarket_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(to='supermarket_app.Product'),
        ),
    ]
