# Generated by Django 3.2.8 on 2023-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('bakery', 'Bakery'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('beverages', 'Beverages')], max_length=20),
        ),
    ]
