# Generated by Django 3.2.8 on 2023-02-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0003_alter_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Unknown', max_length=40),
        ),
    ]
