# Generated by Django 3.2.8 on 2023-02-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0004_auto_20230217_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(default='Producer', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Product Name', max_length=40),
        ),
    ]
