# Generated by Django 3.2.8 on 2023-05-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0004_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket_app.product'),
        ),
    ]
