# Generated by Django 3.2.8 on 2023-03-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0005_auto_20230217_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
